### ISSUE TITLE
problem..

### ISSUE THREAD

**Issue by SlayDaBaus** [JhonforgeGaming/XPBot#2]
undefined:1

SyntaxError: Unexpected end of JSON input
       at Object.parse (native)
etc...

**Comment by ScarlettJFG** [comment]
screenshots? one of error, main, and .JSON

**Comment by ScarlettJFG** [comment]
Also inside the .JSON make sure that there is just { }

**Comment by SlayDaBaus** [comment]
Thanks it was that JSON file but now my bot keeps restarting all the time...

**Comment by SlayDaBaus** [comment]
its not restarting anymore but now im having that Unindentified problem again here's a screenshot https://cdn.discordapp.com/attachments/307866792003633163/327802606015479818/Screenshot_4.png

**Comment by SlayDaBaus** [comment]
its not restarting anymore

**Comment by ScarlettJFG** [comment]
Alright I'll see if I can reproduce it.

**Comment by SlayDaBaus** [comment]
okay thanks!

**Comment by SlayDaBaus** [comment]
I see you are talented at making scripts I am kind of a rookie I guess

**Comment by ScarlettJFG** [comment]
eh I try. Mind you since i did do a fresh install of windows i need to get all the dependencies back...might take awhile

**Comment by ScarlettJFG** [comment]
Just to make sure you have a bot token in there right?

**Comment by SlayDaBaus** [comment]
Yeah I do

**Comment by SlayDaBaus** [comment]
Oh I actually fixed it it doesn't matter anymore the only thing I wish is for the bot to work with nodemon.

**Comment by ScarlettJFG** [comment]
if it isn't i will make it as after researching it i think it would be very useful.

**Comment by ScarlettJFG** [comment]
since i am new to nodemon i didn't get it to work but it looks like it should. Let me know if it does.
